###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
port: 3000
paginate: 7 # it will paginate after this number
per_page: 7
language: 'en-uk'
words_per_minute: 180
color_scheme: Light #Dark #Light 
darkmode_accent_color: "#ff6633"
future: true
search: false

###############################################################################
# Permalinks
permalink: /:year-:month-:day-:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed] #, jekyll-seo-tag, jekyll-resize, jekyll-admin]

feed:
  path: feed.xml

# Page Personal Details
baseurl: /
url: https://biomadeira.github.io
author: Fábio Madeira
title: biomadeira
domain: github.io
description: Bioinformatics and other digressions
image: assets/images/mckayla-crump-3OR-XFzKSBo-unsplash.jpg
# Contacts
email: fabiomadeira@me.com
# Social Usernames for Twitter, Facebook, Github
twitter: biomadeira 
facebook: False 
github: biomadeira

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`

# Disqus
disqus: False
disqus_shortname: username # replace with your disqus username

# Google Analytics 4
google_analytics: G-R9654BB9RP

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
repo: biomadeira.github.io
branch: master
relative_source: /
destination: ./biomadeira.github.io-pages/
production_url:  https://biomadeira.github.io/biomadeira.github.io/
source_url:  https://github.com/biomadeira/biomadeira.github.io/
